### PR TITLE
SLAM Performance Improvements

### PR DESCRIPTION
**Pull request by macmason**
This change is [Reviewable](https://reviewable.io/reviews/thirdwave-ai/cartographer/18)

### CODE REVIEW

**Review by macmason — COMMENTED** [review]
+@boberito25 for review,  +reviewer:@bradleypowers FYI

> *[Reviewable](https://reviewable.io/reviews/thirdwave-ai/cartographer/18#-:-MWb1Gbo3S_xrT75KYV0:b-d3gts9)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @bradleypowers)

**Review by Boberito25 — CHANGES_REQUESTED** [review]
:lgtm: 

> Reviewed 1 of 3 files at r1, 4 of 6 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/thirdwave-ai/cartographer/18#-:-MWb4NZzBuPFBe8hKJ-a:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @bradleypowers and @macmason)

___
*[cartographer/mapping/internal/3d/scan_matching/fast_correlative_scan_matcher_3d.cc, line 96 at r3](https://reviewable.io/reviews/thirdwave-ai/cartographer/18#-MWb3cq11NYTwOxUyusT:-MWb3cq11NYTwOxUyusU:b-lqw42j) ([raw file](https://github.com/thirdwave-ai/cartographer/blob/75ccbdb7a23308170bb4284e18cdbaeb97bf0c9d/cartographer/mapping/internal/3d/scan_matching/fast_correlative_scan_matcher_3d.cc#L96)):*
> ```cpp
>     auto x = Candidate3D(0, Eigen::Array3i::Zero());
>     x.offset.setZero();
>     x.low_resolution_score = -1;
> ```

If we keep this we should document it so no one has to dig up what the failure modes mean (probably in the loop closure pub)

**Review by macmason — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/thirdwave-ai/cartographer/18)* status: all files reviewed, 1 unresolved discussion (waiting on @Boberito25 and @bradleypowers)

___
*[cartographer/mapping/internal/3d/scan_matching/fast_correlative_scan_matcher_3d.cc, line 96 at r3](https://reviewable.io/reviews/thirdwave-ai/cartographer/18#-MWb3cq11NYTwOxUyusT:-MWb6rKX1ZePwJATcGsg:b-896fix) ([raw file](https://github.com/thirdwave-ai/cartographer/blob/75ccbdb7a23308170bb4284e18cdbaeb97bf0c9d/cartographer/mapping/internal/3d/scan_matching/fast_correlative_scan_matcher_3d.cc#L96)):*
<details><summary><i>Previously, Boberito25 (vsunder) wrote…</i></summary><blockquote>

If we keep this we should document it so no one has to dig up what the failure modes mean (probably in the loop closure pub)
</blockquote></details>

Done.

**Review by Boberito25 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/thirdwave-ai/cartographer/18#-:-MWb79QCA-jAh2QzRJEZ:bg7igkv)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @Boberito25 and @bradleypowers)

**Review by Boberito25 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/thirdwave-ai/cartographer/18#-:-MWb7JglBCN8ds0l2Zuh:bnfp4nl)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @Boberito25 and @bradleypowers)

**Review by macmason — COMMENTED** [review]
-reviewer:@bradleypowers 

> *[Reviewable](https://reviewable.io/reviews/thirdwave-ai/cartographer/18#-:-MWb7QVD4ZI2dwnLRf9e:b86zfug)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @Boberito25)

**Review by Boberito25 — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/thirdwave-ai/cartographer/18)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @macmason)

**Pull request merged**
