### PR TITLE
Vikram/work item introspection

### PR DESCRIPTION
**Pull request by Boberito25**
Get details about whats left in the work queue and details about processing that happened before the coming optimization run

---
This change is [Reviewable](https://reviewable.io/reviews/thirdwave-ai/cartographer/13)

### CODE REVIEW

**Review by macmason — CHANGES_REQUESTED** [review]
:lgtm_strong: I was worried this was going to be _really hairy_; looks like you found a way to make it graceful.

What's it teach us? I'm curious about results.

> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/thirdwave-ai/cartographer/13#-:-MVmsOYV5LH_Z4yrL6Ai:ba4qp9n)* status: all files reviewed, 3 unresolved discussions (waiting on @Boberito25, @serraramiro1, and @TrevorDecker)

___
*[cartographer/mapping/internal/work_queue.h, line 31 at r1](https://reviewable.io/reviews/thirdwave-ai/cartographer/13#-MVmrd5GC5wHO7_bagWS:-MVmrd5GC5wHO7_bagWT:b2av5d7) ([raw file](https://github.com/thirdwave-ai/cartographer/blob/5f7e7158ed23aab2ce53144f71a94e6a82c128c3/cartographer/mapping/internal/work_queue.h#L31)):*
> ```objc
> 
> enum WorkItemType {
>   CHANGE_TRAJECTORY_STATE, 
> ```

Small things:

- Prefer `enum class` (see https://abseil.io/tips/86)
- Set actual values (0, 1, 2...) 
- Set the zero to "unknown", because that's the default value.
- Prefer to name constants using kNameFoo.

(You can follow up in a later PR; these are style, not correctness.)
___
*[cartographer/mapping/internal/work_queue.h, line 58 at r1](https://reviewable.io/reviews/thirdwave-ai/cartographer/13#-MVmrwgj2mNRoOaDLl19:-MVmrwgj2mNRoOaDLl1A:bqnnwfc) ([raw file](https://github.com/thirdwave-ai/cartographer/blob/5f7e7158ed23aab2ce53144f71a94e6a82c128c3/cartographer/mapping/internal/work_queue.h#L58)):*
> ```objc
> struct WorkQueueCharacterization {
>   std::chrono::steady_clock::time_point front_of_queue_time;
>   std::map<WorkItemType, size_t> queue_distrobution;
> ```

"distribution", I think.
___
*[cartographer/mapping/internal/work_queue.h, line 64 at r1](https://reviewable.io/reviews/thirdwave-ai/cartographer/13#-MVmrzDT1VctRKH0o5MP:-MVmrzDT1VctRKH0o5MQ:bsqop7n) ([raw file](https://github.com/thirdwave-ai/cartographer/blob/5f7e7158ed23aab2ce53144f71a94e6a82c128c3/cartographer/mapping/internal/work_queue.h#L64)):*
> ```objc
> using WorkQueue = std::deque<WorkItem>;
> 
> WorkQueueCharacterization characterize(const std::unique_ptr<WorkQueue>& queue);
> ```

Probably just take the WorkQueue by const reference, rather than the pointer by const reference.

**Review by serraramiro1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/thirdwave-ai/cartographer/13)* status: 5 of 9 files reviewed, 6 unresolved discussions (waiting on @Boberito25, @macmason, and @TrevorDecker)

___
*[cartographer/mapping/internal/work_queue.h, line 31 at r1](https://reviewable.io/reviews/thirdwave-ai/cartographer/13#-MVmrd5GC5wHO7_bagWS:-MVqESOIA7s5GWLJ7dZv:b-d2dgm5) ([raw file](https://github.com/thirdwave-ai/cartographer/blob/5f7e7158ed23aab2ce53144f71a94e6a82c128c3/cartographer/mapping/internal/work_queue.h#L31)):*
<details><summary><i>Previously, macmason (Mac Mason) wrote…</i></summary><blockquote>

Small things:

- Prefer `enum class` (see https://abseil.io/tips/86)
- Set actual values (0, 1, 2...) 
- Set the zero to "unknown", because that's the default value.
- Prefer to name constants using kNameFoo.

(You can follow up in a later PR; these are style, not correctness.)
</blockquote></details>

+1000 to enum class
___
*[cartographer/mapping/internal/work_queue.h, line 49 at r2](https://reviewable.io/reviews/thirdwave-ai/cartographer/13#-MVqE_Oc0lc_X0uYrICS:-MVqE_Oc0lc_X0uYrICT:bbers0b) ([raw file](https://github.com/thirdwave-ai/cartographer/blob/48aba060e26619c287541ca4488b2494e6c5ab38/cartographer/mapping/internal/work_queue.h#L49)):*
> ```objc
>     kRunOptimization,
>   };
>   using Details = std::map<std::string, size_t>;
> ```

Couldn't this be a std::map<WorkItemType, size_t>? I think that should reduce the amount of if statements down the line.

https://stackoverflow.com/questions/18837857/cant-use-enum-class-as-unordered-map-key
___
*[cartographer/mapping/internal/3d/pose_graph_3d.cc, line 881 at r2](https://reviewable.io/reviews/thirdwave-ai/cartographer/13#-MVqGXXBEl2fPQqmkQXh:-MVqGXXBEl2fPQqmkQXi:bzdjs0b) ([raw file](https://github.com/thirdwave-ai/cartographer/blob/48aba060e26619c287541ca4488b2494e6c5ab38/cartographer/mapping/internal/3d/pose_graph_3d.cc#L881)):*
> ```
> WorkItem::Details
> ```
___
*[cartographer/mapping/internal/constraints/constraint_builder_3d.h, line 51 at r2](https://reviewable.io/reviews/thirdwave-ai/cartographer/13#-MVqGf3M38miHpQWoL9Z:-MVqGf3M38miHpQWoL9_:bomyayh) ([raw file](https://github.com/thirdwave-ai/cartographer/blob/48aba060e26619c287541ca4488b2494e6c5ab38/cartographer/mapping/internal/constraints/constraint_builder_3d.h#L51)):*
> ```objc
> namespace constraints {
> 
> enum LoopClosureSearchType {
> ```

Same applies here

**Comment by serraramiro1** [comment]
:lgtm_strong: 
Some comments but not blocking

**Review by Boberito25 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/thirdwave-ai/cartographer/13)* status: 5 of 9 files reviewed, 6 unresolved discussions (waiting on @Boberito25, @macmason, @serraramiro1, and @TrevorDecker)

___
*[cartographer/mapping/internal/work_queue.h, line 58 at r1](https://reviewable.io/reviews/thirdwave-ai/cartographer/13#-MVmrwgj2mNRoOaDLl19:-MVq_Gze00w4-Voct7sr:b-896fix) ([raw file](https://github.com/thirdwave-ai/cartographer/blob/5f7e7158ed23aab2ce53144f71a94e6a82c128c3/cartographer/mapping/internal/work_queue.h#L58)):*
<details><summary><i>Previously, macmason (Mac Mason) wrote…</i></summary><blockquote>

"distribution", I think.
</blockquote></details>

Done.
___
*[cartographer/mapping/internal/work_queue.h, line 49 at r2](https://reviewable.io/reviews/thirdwave-ai/cartographer/13#-MVqE_Oc0lc_X0uYrICS:-MVq_N5O3X3-oOqpBLOE:b-lapz6d) ([raw file](https://github.com/thirdwave-ai/cartographer/blob/48aba060e26619c287541ca4488b2494e6c5ab38/cartographer/mapping/internal/work_queue.h#L49)):*
<details><summary><i>Previously, serraramiro1 wrote…</i></summary><blockquote>

Couldn't this be a std::map<WorkItemType, size_t>? I think that should reduce the amount of if statements down the line.

https://stackoverflow.com/questions/18837857/cant-use-enum-class-as-unordered-map-key
</blockquote></details>

Ah its because I want to get details on work that are not WorkItems. For example Loop closure search is captured in a ComputeConstraints work item. but it does a bunch more

**Review by Boberito25 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/thirdwave-ai/cartographer/13)* status: 3 of 9 files reviewed, 6 unresolved discussions (waiting on @Boberito25, @macmason, @serraramiro1, and @TrevorDecker)

___
*[cartographer/mapping/internal/work_queue.h, line 31 at r1](https://reviewable.io/reviews/thirdwave-ai/cartographer/13#-MVmrd5GC5wHO7_bagWS:-MVrPadk86nFeKTYQ8px:b-896fix) ([raw file](https://github.com/thirdwave-ai/cartographer/blob/5f7e7158ed23aab2ce53144f71a94e6a82c128c3/cartographer/mapping/internal/work_queue.h#L31)):*
<details><summary><i>Previously, serraramiro1 wrote…</i></summary><blockquote>

+1000 to enum class
</blockquote></details>

Done.
___
*[cartographer/mapping/internal/work_queue.h, line 64 at r1](https://reviewable.io/reviews/thirdwave-ai/cartographer/13#-MVmrzDT1VctRKH0o5MP:-MVrPc47CehROEVE3-Xw:b8npvyb) ([raw file](https://github.com/thirdwave-ai/cartographer/blob/5f7e7158ed23aab2ce53144f71a94e6a82c128c3/cartographer/mapping/internal/work_queue.h#L64)):*
<details><summary><i>Previously, macmason (Mac Mason) wrote…</i></summary><blockquote>

Probably just take the WorkQueue by const reference, rather than the pointer by const reference.
</blockquote></details>

The work queue is constructed in a unique pointer. Does it make sense to dereference and pass
___
*[cartographer/mapping/internal/constraints/constraint_builder_3d.h, line 51 at r2](https://reviewable.io/reviews/thirdwave-ai/cartographer/13#-MVqGf3M38miHpQWoL9Z:-MVrPoHS-LP6mPPjKuXe:b-896fix) ([raw file](https://github.com/thirdwave-ai/cartographer/blob/48aba060e26619c287541ca4488b2494e6c5ab38/cartographer/mapping/internal/constraints/constraint_builder_3d.h#L51)):*
<details><summary><i>Previously, serraramiro1 wrote…</i></summary><blockquote>

Same applies here
</blockquote></details>

Done.

**Review by macmason — CHANGES_REQUESTED** [review]
:lgtm_strong: 

> Reviewed 2 of 4 files at r2, 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/thirdwave-ai/cartographer/13#-:-MVrZSdG35n10XvjkdP5:b-uwkowd)* status: all files reviewed, 4 unresolved discussions (waiting on @Boberito25, @serraramiro1, and @TrevorDecker)

___
*[cartographer/mapping/internal/work_queue.h, line 31 at r1](https://reviewable.io/reviews/thirdwave-ai/cartographer/13#-MVmrd5GC5wHO7_bagWS:-MVrYebt1D0yVemvXLeX:bqlb5w2) ([raw file](https://github.com/thirdwave-ai/cartographer/blob/5f7e7158ed23aab2ce53144f71a94e6a82c128c3/cartographer/mapping/internal/work_queue.h#L31)):*
<details><summary><i>Previously, Boberito25 (vsunder) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please make `UNLABELED_ITEM` the first entry.
___
*[cartographer/mapping/internal/work_queue.h, line 64 at r1](https://reviewable.io/reviews/thirdwave-ai/cartographer/13#-MVmrzDT1VctRKH0o5MP:-MVrYiaqEnUsJ09OylcL:b9ilb7v) ([raw file](https://github.com/thirdwave-ai/cartographer/blob/5f7e7158ed23aab2ce53144f71a94e6a82c128c3/cartographer/mapping/internal/work_queue.h#L64)):*
<details><summary><i>Previously, Boberito25 (vsunder) wrote…</i></summary><blockquote>

The work queue is constructed in a unique pointer. Does it make sense to dereference and pass
</blockquote></details>

It isn't a big deal here, but as a rule of thumb, you don't want to make memory management decisions for your users. Right now, `WorkQueue` has to be behind a unique_ptr (not a regular pointer, not a value, not a shared pointer; only a unique_ptr) so we're forcing something on the user of this function. Using a `const` reference lets the user store the thing however they want.

Now, in practice, we're our only user, and it works this way, so it won't actually matter in practice. 

Up to you!

**Review by Boberito25 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/thirdwave-ai/cartographer/13)* status: 8 of 9 files reviewed, 4 unresolved discussions (waiting on @macmason, @serraramiro1, and @TrevorDecker)

___
*[cartographer/mapping/internal/3d/pose_graph_3d.cc, line 881 at r2](https://reviewable.io/reviews/thirdwave-ai/cartographer/13#-MVqGXXBEl2fPQqmkQXh:-MVrbOPX3Qzb_OcNJ6yH:b-896fix) ([raw file](https://github.com/thirdwave-ai/cartographer/blob/48aba060e26619c287541ca4488b2494e6c5ab38/cartographer/mapping/internal/3d/pose_graph_3d.cc#L881)):*
<details><summary><i>Previously, serraramiro1 wrote…</i></summary><blockquote>

> ```
> WorkItem::Details
> ```

</blockquote></details>

Done.

**Review by macmason — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/thirdwave-ai/cartographer/13)* status: all files reviewed, 3 unresolved discussions (waiting on @serraramiro1 and @TrevorDecker)

**Pull request merged**
