### PR TITLE
Add map_builder_callbacks

### PR DESCRIPTION
**Pull request by Boberito25**
This change is [Reviewable](https://reviewable.io/reviews/thirdwave-ai/cartographer/7)

### CODE REVIEW

**Review by macmason — COMMENTED** [review]
Tell me about all these deletes.

> Reviewed 18 of 107 files at r1.
> *[Reviewable](https://reviewable.io/reviews/thirdwave-ai/cartographer/7#-:-MSjZAWiErUkLo2utyH7:bqp47mb)* status: 18 of 107 files reviewed, all discussions resolved (waiting on @macmason)

**Comment by Boberito25** [comment]
I think I might want to report on failed loop closure searches as well

**Comment by Boberito25** [comment]
> Tell me about all these deletes.
> 
> > Reviewed 18 of 107 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/thirdwave-ai/cartographer/7#-:-MSjZAWiErUkLo2utyH7:bqp47mb)_ status: 18 of 107 files reviewed, all discussions resolved (waiting on @macmason)

Deleted cartographer/cloud to get everything building faster >.>

**Review by macmason — CHANGES_REQUESTED** [review]
(Told me offline.)

:lgtm_strong: and so this needs a truck-test. This one is the wrong repo, so let's make sure it gets it in the mainline.

> Reviewed 89 of 107 files at r1.
> *[Reviewable](https://reviewable.io/reviews/thirdwave-ai/cartographer/7#-:-MSjdoiv4WKJjRDNHuB3:box3ucz)* status: all files reviewed, 1 unresolved discussion (waiting on @Boberito25)

___
*[cartographer/mapping/internal/constraints/constraint_builder_3d.cc, line 116 at r1](https://reviewable.io/reviews/thirdwave-ai/cartographer/7#-MSjdDgH1Q9b5kjBziJ4:-MSjdDgH1Q9b5kjBziJ5:bj2enex) ([raw file](https://github.com/thirdwave-ai/cartographer/blob/962752ee32bb2552a03318f41d58826abb4fd7c2/cartographer/mapping/internal/constraints/constraint_builder_3d.cc#L116)):*
> ```cpp
>     const Eigen::Quaterniond& global_submap_rotation,
>     std::function<void(
>       scan_matching::FastCorrelativeScanMatcher3D::Result,  // Course search
> ```

"coarse"?

**Review by macmason — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/thirdwave-ai/cartographer/7)* status: all files reviewed, 2 unresolved discussions (waiting on @Boberito25)

___
*[cartographer/mapping/internal/constraints/constraint_builder_3d.h, line 84 at r2](https://reviewable.io/reviews/thirdwave-ai/cartographer/7#-MSofj3h3NHdtjiWrp7B:-MSofj3i3fg9uQB1CKJq:b-bg5xdx) ([raw file](https://github.com/thirdwave-ai/cartographer/blob/85d4f4ecf9edc6406c0b33126abae8e50922c776/cartographer/mapping/internal/constraints/constraint_builder_3d.h#L84)):*
> ```objc
>                           const transform::Rigid3d& global_submap_pose,
>                           std::function<void(
>                             scan_matching::FastCorrelativeScanMatcher3D::Result,  // Course search
> ```

"coarse"

Gonna keep getting you on this one... ;-)
___
*[cartographer/mapping/internal/constraints/constraint_builder_3d_test.cc, line 91 at r2](https://reviewable.io/reviews/thirdwave-ai/cartographer/7#-MSofpAP6WaLgC4EC4jM:-MSofpAP6WaLgC4EC4jN:b3yir24) ([raw file](https://github.com/thirdwave-ai/cartographer/blob/85d4f4ecf9edc6406c0b33126abae8e50922c776/cartographer/mapping/internal/constraints/constraint_builder_3d_test.cc#L91)):*
> ```cpp
>       constraint_builder_->MaybeAddConstraint(
>           submap_id, &submap, NodeId{0, 0}, node_data.get(),
>           transform::Rigid3d::Identity(), transform::Rigid3d::Identity(), nullptr);
> ```

Consider having this argument default to nullptr. Up to you.

**Pull request merged**
